# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# Remanentia — User service installer

"""Install user-level supervised services for Remanentia.

The checked-in file is an installer, not a host-specific unit file: it
renders the current checkout path into ``~/.config/systemd/user`` so
public source control does not carry local machine paths.
"""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

from store_paths import StorePaths, resolve_store_paths

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_EMBEDDING_BASE_URL = "http://127.0.0.1:8082/v1"
DEFAULT_EMBEDDING_MODEL = "nomic-embed"
DEFAULT_EMBEDDING_VECTOR_SIZE = "768"
DEFAULT_PUBLIC_VECTOR_SOURCES = "paper"
DEFAULT_PUBLIC_VECTOR_PATH_PREFIXES = "paper"
DEFAULT_PUBLIC_VECTOR_MAX_TEXT_CHARS = "800"


def _python_path(repo: Path) -> Path:
    """Return the checkout virtualenv Python when present, else ``python3``."""
    venv_python = repo / ".venv" / "bin" / "python"
    if venv_python.exists():
        return venv_python
    return Path("python3")


def _env_lines(values: dict[str, str]) -> str:
    """Render systemd ``Environment=`` lines with minimal quote escaping."""
    lines = []
    for key, value in values.items():
        escaped = value.replace('"', '\\"')
        lines.append(f'Environment="{key}={escaped}"')
    return "\n".join(lines)


def _store_env(paths: StorePaths) -> dict[str, str]:
    """Return memory-store selection variables for generated units."""
    return {
        "REMANENTIA_BASE": str(paths.base),
        "REMANENTIA_STIMULI_DIR": str(paths.stimuli_dir),
    }


def _api_unit(
    repo: Path,
    python: Path,
    paths: StorePaths,
    host: str,
    port: int,
    embedding_base_url: str,
    embedding_model: str,
    public_vector_sources: str,
    public_vector_path_prefixes: str,
    public_vector_max_text_chars: str,
) -> str:
    env = _env_lines(
        {
            "PYTHONUNBUFFERED": "1",
            **_store_env(paths),
            "REMANENTIA_EMBEDDING_BASE_URL": embedding_base_url,
            "REMANENTIA_EMBEDDING_MODEL": embedding_model,
            "REMANENTIA_PUBLIC_VECTOR_SOURCES": public_vector_sources,
            "REMANENTIA_PUBLIC_VECTOR_PATH_PREFIXES": public_vector_path_prefixes,
            "REMANENTIA_PUBLIC_VECTOR_MAX_TEXT_CHARS": public_vector_max_text_chars,
        }
    )
    return f"""# Generated by REMANENTIA tools/install_user_services.py
[Unit]
Description=Remanentia API
After=network-online.target

[Service]
Type=simple
WorkingDirectory={repo}
{env}
ExecStart={python} cli.py serve --host {host} --port {port}
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
"""


def _worker_unit(
    repo: Path,
    python: Path,
    paths: StorePaths,
    interval_s: float,
    embedding_base_url: str,
    embedding_model: str,
    embedding_vector_size: str,
) -> str:
    env = _env_lines(
        {
            "PYTHONUNBUFFERED": "1",
            **_store_env(paths),
            "REMANENTIA_EMBEDDING_BASE_URL": embedding_base_url,
            "REMANENTIA_EMBEDDING_MODEL": embedding_model,
            "REMANENTIA_EMBEDDING_VECTOR_SIZE": embedding_vector_size,
        }
    )
    return f"""# Generated by REMANENTIA tools/install_user_services.py
[Unit]
Description=Remanentia scheduled vector refresh worker
After=network-online.target remanentia-api.service

[Service]
Type=simple
WorkingDirectory={repo}
{env}
ExecStart={python} -m vector_pipeline watch --index-dir {paths.vector_index_dir} --heartbeat-path {paths.state_dir / "vector_refresh_worker.json"} --interval-s {interval_s}
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
"""


def _freshness_service(repo: Path, python: Path, paths: StorePaths) -> str:
    """Render the oneshot unit that checks index drift and persists a report.

    The refresh worker can stall silently — an embedding backend goes down, a
    disk migration strands its heartbeat — and the retrieval index freezes on an
    old worldview while findings keep arriving. That is exactly the failure that
    went unnoticed for eight weeks. This oneshot runs the freshness gate, writes
    its verdict to the selected store, and exits non-zero when the drift exceeds
    tolerance, so its paired daily timer turns a stall into a ``failed`` unit
    within a day instead of weeks. It reads only mtimes; it never rebuilds.
    """
    env = _env_lines({"PYTHONUNBUFFERED": "1", **_store_env(paths)})
    return f"""# Generated by REMANENTIA tools/install_user_services.py
[Unit]
Description=Remanentia index-freshness watchdog

[Service]
Type=oneshot
WorkingDirectory={repo}
{env}
ExecStart={python} -m index_freshness --report {paths.freshness_report}
"""


def _freshness_timer() -> str:
    """Render the daily timer that fires the index-freshness watchdog.

    ``Persistent=true`` runs a missed check after the machine wakes, so a
    weekend powered down does not blind the watchdog; the randomised delay keeps
    it from contending with other login-time jobs.
    """
    return """# Generated by REMANENTIA tools/install_user_services.py
[Unit]
Description=Daily Remanentia index-freshness watchdog

[Timer]
OnCalendar=daily
Persistent=true
RandomizedDelaySec=600
Unit=remanentia-index-freshness.service

[Install]
WantedBy=timers.target
"""


def install_units(args: argparse.Namespace) -> list[Path]:
    """Write Remanentia user service units and return their paths."""
    repo = Path(args.repo).resolve()
    user_dir = Path(args.user_dir).expanduser()
    user_dir.mkdir(parents=True, exist_ok=True)
    python = _python_path(repo)
    store_base = Path(args.base).expanduser().resolve() if args.base else repo
    stimuli_dir = Path(args.stimuli_dir).expanduser().resolve() if args.stimuli_dir else None
    paths = resolve_store_paths(base=store_base, stimuli_dir=stimuli_dir)

    units = {
        "remanentia-api.service": _api_unit(
            repo,
            python,
            paths,
            args.host,
            args.port,
            args.embedding_base_url,
            args.embedding_model,
            args.public_vector_sources,
            args.public_vector_path_prefixes,
            args.public_vector_max_text_chars,
        ),
        "remanentia-vector-worker.service": _worker_unit(
            repo,
            python,
            paths,
            args.interval_s,
            args.embedding_base_url,
            args.embedding_model,
            args.embedding_vector_size,
        ),
        "remanentia-index-freshness.service": _freshness_service(
            repo,
            python,
            paths,
        ),
        "remanentia-index-freshness.timer": _freshness_timer(),
    }
    written = []
    for name, text in units.items():
        path = user_dir / name
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


def _systemctl(*args: str) -> None:
    """Run ``systemctl --user`` with *args* and fail on errors."""
    subprocess.run(["systemctl", "--user", *args], check=True)


def main(argv: list[str] | None = None) -> int:
    """Install Remanentia user service units."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=str(REPO_ROOT))
    parser.add_argument(
        "--base",
        default=None,
        help="Memory-store base to export as REMANENTIA_BASE in generated units",
    )
    parser.add_argument(
        "--stimuli-dir",
        default=None,
        help="Stimuli firehose directory to export as REMANENTIA_STIMULI_DIR",
    )
    parser.add_argument("--user-dir", default=str(Path.home() / ".config/systemd/user"))
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8001)
    parser.add_argument("--interval-s", type=float, default=900.0)
    parser.add_argument("--embedding-base-url", default=DEFAULT_EMBEDDING_BASE_URL)
    parser.add_argument("--embedding-model", default=DEFAULT_EMBEDDING_MODEL)
    parser.add_argument("--embedding-vector-size", default=DEFAULT_EMBEDDING_VECTOR_SIZE)
    parser.add_argument("--public-vector-sources", default=DEFAULT_PUBLIC_VECTOR_SOURCES)
    parser.add_argument(
        "--public-vector-path-prefixes",
        default=DEFAULT_PUBLIC_VECTOR_PATH_PREFIXES,
    )
    parser.add_argument(
        "--public-vector-max-text-chars",
        default=DEFAULT_PUBLIC_VECTOR_MAX_TEXT_CHARS,
    )
    parser.add_argument(
        "--enable-worker",
        action="store_true",
        help=(
            "Also enable the vector refresh worker so it starts on login. The "
            "worker's first cycle refreshes the index, which can be heavy on a "
            "large corpus, so worker activation is opt-in and separate from the "
            "always-safe freshness watchdog."
        ),
    )
    parser.add_argument(
        "--start",
        action="store_true",
        help="Restart the API and the vector worker now (implies --enable-worker).",
    )
    parser.add_argument("--no-systemctl", action="store_true", help="Only write unit files")
    args = parser.parse_args(argv)

    written = install_units(args)
    for path in written:
        print(path)

    if not args.no_systemctl:
        _systemctl("daemon-reload")
        # The read-only freshness watchdog and the API are always enabled and the
        # watchdog timer is started — neither rebuilds the index. The refresh
        # worker (whose first cycle can be a heavy rebuild) is gated behind an
        # explicit flag so supervision can be installed without triggering work.
        _systemctl("enable", "remanentia-api.service", "remanentia-index-freshness.timer")
        _systemctl("start", "remanentia-index-freshness.timer")
        if args.enable_worker or args.start:
            _systemctl("enable", "remanentia-vector-worker.service")
        if args.start:
            _systemctl("restart", "remanentia-api.service", "remanentia-vector-worker.service")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
